# coding: utf-8

"""
    OpenAI API

    The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

    The version of the OpenAPI document: 2.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class AuditLogEventType(str, Enum):
    """
    The event type.
    """

    """
    allowed enum values
    """
    API_KEY_PERIOD_CREATED = 'api_key.created'
    API_KEY_PERIOD_UPDATED = 'api_key.updated'
    API_KEY_PERIOD_DELETED = 'api_key.deleted'
    INVITE_PERIOD_SENT = 'invite.sent'
    INVITE_PERIOD_ACCEPTED = 'invite.accepted'
    INVITE_PERIOD_DELETED = 'invite.deleted'
    LOGIN_PERIOD_SUCCEEDED = 'login.succeeded'
    LOGIN_PERIOD_FAILED = 'login.failed'
    LOGOUT_PERIOD_SUCCEEDED = 'logout.succeeded'
    LOGOUT_PERIOD_FAILED = 'logout.failed'
    ORGANIZATION_PERIOD_UPDATED = 'organization.updated'
    PROJECT_PERIOD_CREATED = 'project.created'
    PROJECT_PERIOD_UPDATED = 'project.updated'
    PROJECT_PERIOD_ARCHIVED = 'project.archived'
    SERVICE_ACCOUNT_PERIOD_CREATED = 'service_account.created'
    SERVICE_ACCOUNT_PERIOD_UPDATED = 'service_account.updated'
    SERVICE_ACCOUNT_PERIOD_DELETED = 'service_account.deleted'
    USER_PERIOD_ADDED = 'user.added'
    USER_PERIOD_UPDATED = 'user.updated'
    USER_PERIOD_DELETED = 'user.deleted'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AuditLogEventType from a JSON string"""
        return cls(json.loads(json_str))


